language: node_js
node_js:
  - 'lts/*'
sudo: false
cache: yarn
before_install:
  - npm install --global nyc codecov coveralls
script:
  - yarn build
  - nyc npm run test-ci
after_script:
  - nyc report --reporter=text-lcov | coveralls
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
