language: node_js
node_js:
  - "lts/*"
  - "12"
  - "10"
  - "8"
sudo: false
cache: yarn
before_install:
  - npm install --global yarn nyc
script:
  - npm run lint
  - npm run build
  - nyc npm run test
after_script:
  - npm install --global codecov coveralls
  - nyc report --reporter=text-lcov | coveralls
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
