env:
  # fix windows timeout
  # https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
  - YARN_GPG=no
os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - "lts/*"
  - "12"
  - "10"
  - "8"
cache:
  yarn: true
before_install:
  - npm install --global yarn nyc
install:
  - yarn
script:
  - npm run lint
  - npm run build
  - yarn test-coverage
after_script:
  - npm install --global coveralls codecov
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codecov
