language: node_js
node_js:
  - "lts/*"
cache:
  yarn: true
before_install:
  - npm install --global yarn nyc
install:
  - yarn
script:
  - yarn lint
  - yarn build
  - yarn test-coverage
after_script:
  - npm install --global coveralls codecov
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codecov
